spring:
  application:
    name: SecureLoginPUC

  thymeleaf:
    cache: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

app:
  users:
    file: ${USERS_FILE:./data/users.json}

  seed:
    user:
      username: rafael
      email: rafael@example.com
      password: ${SEED_USER_PASSWORD:1234}
      role: USER
    admin:
      username: admin
      email: admin@example.com
      password: ${SEED_ADMIN_PASSWORD:admin}
      role: ADMIN

  base-url: ${APP_BASE_URL:http://localhost:8080}
